
flag_codes = {
  "ABW": "Aruba",
  "AFG": "Afghanistan",
  "AGO": "Angola",
  "AIA": "Anguilla",
  "AL": "Arab League",
  "ALA": "Åland Islands",
  "ALB": "Albania",
  "ANA": "Authorised Neutral Athletes",
  "AND": "Andorra",
  "ANT": "Netherlands Antilles",
  "ANZ": "Australasia",
  "ARE": "United Arab Emirates",
  "ARG": "Argentina",
  "ARM": "Armenia",
  "ASM": "American Samoa",
  "ATA": "Antarctica",
  "ATF": "French Southern and Antarctic Lands",
  "ATG": "Antigua and Barbuda",
  "AUS": "Australia",
  "AUT": "Austria",
  "AZE": "Azerbaijan",
  "BDI": "Burundi",
  "BEL": "Belgium",
  "BEN": "Benin",
  "BES": "Caribbean Netherlands",
  "BFA": "Burkina Faso",
  "BGD": "Bangladesh",
  "BGR": "Bulgaria",
  "BHR": "Bahrain",
  "BHS": "Bahamas",
  "BIH": "Bosnia and Herzegovina",
  "BIR": "Burma",
  "BLM": "Saint Barthélemy",
  "BLR": "Belarus",
  "BLZ": "Belize",
  "BMU": "Bermuda",
  "BOE": "Bonaire",
  "BOH": "Bohemia",
  "BOL": "Bolivia",
  "BRA": "Brazil",
  "BRB": "Barbados",
  "BRN": "Brunei",
  "BTN": "Bhutan",
  "BVT": "Bouvet Island",
  "BWA": "Botswana",
  "CAF": "Central African Republic",
  "CAN": "Canada",
  "CCK": "Cocos (Keeling) Islands",
  "CEN": "Central America",
  "CHE": "Switzerland",
  "CHL": "Chile",
  "CHN": "China",
  "CHN-MLD": "Mainland China",
  "CHN-ROC": "Taiwan",
  "CHNML": "Mainland China",
  "CIP": "International Paralympic Committee",
  "CIS": "CIS",
  "CIV": "Ivory Coast",
  "CMR": "Cameroon",
  "COD": "Democratic Republic of the Congo",
  "COD2": "DR of the Congo",
  "COE": "Council of Europe",
  "COG": "Republic of the Congo",
  "COK": "Cook Islands",
  "COL": "Colombia",
  "COM": "Comoros",
  "Country data US-FL": "Florida",
  "CPV": "Cape Verde",
  "CRI": "Costa Rica",
  "CSK": "Czechoslovakia",
  "CSR": "Czechoslovak Socialist Republic",
  "CUB": "Cuba",
  "CUW": "Curaçao",
  "CXR": "Christmas Island",
  "CYM": "Cayman Islands",
  "CYP": "Cyprus",
  "CZE": "Czech Republic",
  "DAG": "Dagestan",
  "DDR": "East Germany",
  "DEU": "Germany",
  "DJI": "Djibouti",
  "DMA": "Dominica",
  "DNK": "Denmark",
  "DNR": "Donetsk People's Republic",
  "DOM": "Dominican Republic",
  "DPR": "Donetsk People's Republic",
  "DPRK": "North Korea",
  "DRC": "Democratic Republic of the Congo",
  "DZA": "Algeria",
  "ECU": "Ecuador",
  "EGY": "Egypt",
  "ENG": "England",
  "ERI": "Eritrea",
  "ESH": "Western Sahara",
  "ESP": "Spain",
  "EST": "Estonia",
  "ETH": "Ethiopia",
  "ETM": "East Timor",
  "EU": "European Union",
  "EUA": "Germany",
  "EUR": "Europe",
  "FHR": "Republic of Haiti (1859–1957)",
  "FIN": "Finland",
  "FJI": "Fiji",
  "FLK": "Falkland Islands",
  "FR-YUG": "Yugoslavia",
  "FRA": "France",
  "FRG": "West Germany",
  "FRO": "Faroe Islands",
  "FSM": "Federated States of Micronesia",
  "GAB": "Gabon",
  "GBR": "United Kingdom",
  "GBR2": "Great Britain",
  "GDL": "Guadeloupe",
  "GEO": "Georgia",
  "GGY": "Guernsey",
  "GHA": "Ghana",
  "GIB": "Gibraltar",
  "GIN": "Guinea",
  "GLP": "Guadeloupe",
  "GMB": "Gambia",
  "GNB": "Guinea-Bissau",
  "GNQ": "Equatorial Guinea",
  "GRC": "Greece",
  "GRD": "Grenada",
  "GRL": "Greenland",
  "GTM": "Guatemala",
  "GUF": "French Guiana",
  "GUM": "Guam",
  "GUY": "Guyana",
  "GYF": "French Guiana",
  "HKG": "Hong Kong",
  "HKG-CHN": "Hong Kong, China",
  "HMD": "Heard Island and McDonald Islands",
  "HND": "Honduras",
  "HPR": "Hungarian People's Republic",
  "HRV": "Croatia",
  "HTI": "Haiti",
  "HUN": "Hungary",
  "IDN": "Indonesia",
  "IMN": "Isle of Man",
  "IND": "India",
  "IOC": "International Olympic Committee",
  "IOT": "British Indian Ocean Territory",
  "IRL": "Ireland",
  "IRL4": "Ireland",
  "IRN": "Iran",
  "IRQ": "Iraq",
  "ISL": "Iceland",
  "ISR": "Israel",
  "ITA": "Italy",
  "JAM": "Jamaica",
  "JEY": "Jersey",
  "JOR": "Jordan",
  "JAP": "Japan",
  "JPN": "Japan",
  "KAZ": "Kazakhstan",
  "KEN": "Kenya",
  "KGZ": "Kyrgyzstan",
  "KHM": "Cambodia",
  "KIR": "Kiribati",
  "KNA": "Saint Kitts and Nevis",
  "KOR": "South Korea",
  "KOS": "Kosovo",
  "KWT": "Kuwait",
  "LAO": "Laos",
  "LBN": "Lebanon",
  "LBR": "Liberia",
  "LBY": "Libya",
  "LCA": "Saint Lucia",
  "LIE": "Liechtenstein",
  "LKA": "Sri Lanka",
  "LPDR": "Lao People's Democratic Republic",
  "LSO": "Lesotho",
  "LTU": "Lithuania",
  "LUX": "Luxembourg",
  "LVA": "Latvia",
  "MAC": "Macau",
  "MAC-CHN": "Macau, China",
  "MAF": "Saint Martin",
  "MAR": "Morocco",
  "MCO": "Monaco",
  "MD": "Republic of Moldova",
  "MDA": "Moldova",
  "MDA-PMR": "Transnistria",
  "MDG": "Madagascar",
  "MDV": "Maldives",
  "MENA": "Middle East and North Africa",
  "MEX": "Mexico",
  "MHL": "Marshall Islands",
  "MIC": "Federated States of Micronesia",
  "MKD": "North Macedonia",
  "MLI": "Mali",
  "MLT": "Malta",
  "MMR": "Myanmar",
  "MNE": "Montenegro",
  "MNG": "Mongolia",
  "MNP": "Northern Mariana Islands",
  "MOZ": "Mozambique",
  "MPR": "Mongolian People's Republic",
  "MRT": "Mauritania",
  "MSR": "Montserrat",
  "MT": "Malta",
  "MTQ": "Martinique",
  "MUS": "Mauritius",
  "MWI": "Malawi",
  "MYS": "Malaysia",
  "MYT": "Mayotte",
  "NAM": "Namibia",
  "NCL": "New Caledonia",
  "NER": "Niger",
  "NFK": "Norfolk Island",
  "NGA": "Nigeria",
  "NIC": "Nicaragua",
  "NIR": "Northern Ireland",
  "NIU": "Niue",
  "NLD": "Netherlands",
  "NOR": "Norway",
  "NPL": "Nepal",
  "NRU": "Nauru",
  "NZL": "New Zealand",
  "OMN": "Oman",
  "PAK": "Pakistan",
  "PAN": "Panama",
  "PCN": "Pitcairn Islands",
  "PER": "Peru",
  "PHL": "Philippines",
  "PLW": "Palau",
  "PNG": "Papua New Guinea",
  "POL": "Poland",
  "PRB": "People's Republic of Bulgaria",
  "PRC": "People's Republic of China",
  "PRI": "Puerto Rico",
  "PRK": "North Korea",
  "PRT": "Portugal",
  "PRY": "Paraguay",
  "PSE": "Palestine",
  "PYF": "French Polynesia",
  "QAT": "Qatar",
  "REU": "Réunion",
  "ROC": "Republic of China",
  "ROC-TW": "Republic of China (Taiwan)",
  "ROK": "South Korea",
  "ROU": "Romania",
  "RSR": "Socialist Republic of Romania",
  "RUS": "Russia",
  "RWA": "Rwanda",
  "SADR": "Sahrawi Arab Democratic Republic",
  "SAU": "Saudi Arabia",
  "SCG": "Serbia and Montenegro",
  "SCO": "Scotland",
  "SDN": "Sudan",
  "SEN": "Senegal",
  "SGP": "Singapore",
  "SGS": "South Georgia and the South Sandwich Islands",
  "SHN": "Saint Helena, Ascension and Tristan da Cunha",
  "SJM": "Svalbard and Jan Mayen",
  "SLB": "Solomon Islands",
  "SLE": "Sierra Leone",
  "SLV": "El Salvador",
  "SMR": "San Marino",
  "SMR/Italy": "San Marino",
  "SOM": "Somalia",
  "SPM": "Saint Pierre and Miquelon",
  "SRB": "Serbia",
  "SSD": "South Sudan",
  "STP": "São Tomé and Príncipe",
  "SUR": "Suriname",
  "SVK": "Slovakia",
  "SVN": "Slovenia",
  "SWE": "Sweden",
  "SWZ": "Swaziland",
  "SXM": "Sint Maarten",
  "SYC": "Seychelles",
  "SYR": "Syria",
  "TAH": "Tahiti",
  "TCA": "Turks and Caicos Islands",
  "TCD": "Chad",
  "TGO": "Togo",
  "THA": "Thailand",
  "TJK": "Tajikistan",
  "TKL": "Tokelau",
  "TKM": "Turkmenistan",
  "TLS": "Timor-Leste",
  "TON": "Tonga",
  "TPE": "Chinese Taipei",
  "TRNC": "Northern Cyprus",
  "TTO": "Trinidad and Tobago",
  "TUN": "Tunisia",
  "TUR": "Turkey",
  "TUV": "Tuvalu",
  "TWN": "Taiwan",
  "TWN-ROC": "Taiwan (Republic of China)",
  "TZA": "Tanzania",
  "UAR": "United Arab Republic",
  "UGA": "Uganda",
  "UKR": "Ukraine",
  "UMI": "United States Minor Outlying Islands",
  "UNO": "United Nations",
  "URS": "Soviet Union",
  "URY": "Uruguay",
  "USA": "United States",
  "UZB": "Uzbekistan",
  "VAT": "Vatican City",
  "VCT": "Saint Vincent and the Grenadines",
  "VEN": "Venezuela",
  "VGB": "British Virgin Islands",
  "VIR": "United States Virgin Islands",
  "VNM": "Vietnam",
  "VUT": "Vanuatu",
  "WAL": "Wales",
  "WLF": "Wallis and Futuna",
  "WSM": "Samoa",
  "YEM": "Yemen",
  "YUG": "Yugoslavia",
  "ZAF": "South Africa",
  "ZAI": "Zaire",
  "ZMB": "Zambia",
  "ZWE": "Zimbabwe"
}
